authors:
  suki:
    name: Suki (Kyoshi's No. 1 Fan)
    description: "I am a warrior, but I'm a girl too."
    avatar: https://raw.githubusercontent.com/FanAndSwordGit/FanAndSwordFansite/refs/heads/main/docs/blog/assets/author-profiles/suki-profile.jpg